#!/usr/bin/env python3
"""Download self-hosted webfonts (latin subset, woff2) into public/fonts and
generate src/styles/fonts.css. Re-run to refresh. Design system: Marble & Machine."""
import base64, re, os, urllib.request

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# family query -> css2 fragment
FAMILIES = [
    "Cormorant+Garamond:ital,wght@0,400;0,600;1,400",
    "Sora:wght@400;500;600",
    "IBM+Plex+Mono:wght@400;500",
]

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.dirname(HERE)
FONT_DIR = os.path.join(WEB, "public", "fonts")
CSS_OUT = os.path.join(WEB, "src", "styles", "fonts.css")

os.makedirs(FONT_DIR, exist_ok=True)

FACE_RE = re.compile(r"@font-face\s*{([^}]+)}", re.S)


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def prop(block, name):
    m = re.search(name + r"\s*:\s*([^;]+);", block)
    return m.group(1).strip() if m else None


def slug(family):
    return re.sub(r"[^a-z0-9]+", "-", family.strip("'\" ").lower()).strip("-")


faces, seen = [], set()
for fam in FAMILIES:
    css = fetch(f"https://fonts.googleapis.com/css2?family={fam}&display=swap").decode()
    for block in FACE_RE.findall(css):
        if "U+0000-00FF" not in (prop(block, "unicode-range") or ""):
            continue
        family = prop(block, "font-family")
        style = prop(block, "font-style") or "normal"
        weight = prop(block, "font-weight") or "400"
        m = re.search(r"url\((https://[^)]+\.woff2)\)", prop(block, "src") or "")
        if not m:
            continue
        key = (family, style, weight)
        if key in seen:
            continue
        seen.add(key)
        name = f"{slug(family)}-{weight}{'-italic' if style == 'italic' else ''}.woff2"
        with open(os.path.join(FONT_DIR, name), "wb") as f:
            f.write(fetch(m.group(1)))
        faces.append(
            f"@font-face {{\n  font-family: {family};\n  font-style: {style};\n"
            f"  font-weight: {weight};\n  font-display: swap;\n"
            f"  src: url('/fonts/{name}') format('woff2');\n}}"
        )
        print(f"  {name}")

with open(CSS_OUT, "w") as f:
    f.write("/* Generated by scripts/fetch-fonts.py — do not edit by hand. */\n\n")
    f.write("\n\n".join(faces) + "\n")
print(f"\nWrote {CSS_OUT} ({len(faces)} faces) + {FONT_DIR}")
